// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIUdiul9N-Lr7h4HJdQ-QSVE-_lO80GGQ',
    appId: '1:634110584934:web:29a26f5183149ec0eca5a7',
    messagingSenderId: '634110584934',
    projectId: 'raabta-8a961',
    authDomain: 'raabta-8a961.firebaseapp.com',
    storageBucket: 'raabta-8a961.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkchWQ2a3bwJbOgXF-MOsdQjd-9k5gdOg',
    appId: '1:634110584934:android:abfeeb498bd95e45eca5a7',
    messagingSenderId: '634110584934',
    projectId: 'raabta-8a961',
    storageBucket: 'raabta-8a961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0MXj-fsiDOgByZZJYcNSouWutHy7NLQ',
    appId: '1:634110584934:ios:f2dd0fab21296aaaeca5a7',
    messagingSenderId: '634110584934',
    projectId: 'raabta-8a961',
    storageBucket: 'raabta-8a961.firebasestorage.app',
    iosBundleId: 'com.example.raabta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0MXj-fsiDOgByZZJYcNSouWutHy7NLQ',
    appId: '1:634110584934:ios:f2dd0fab21296aaaeca5a7',
    messagingSenderId: '634110584934',
    projectId: 'raabta-8a961',
    storageBucket: 'raabta-8a961.firebasestorage.app',
    iosBundleId: 'com.example.raabta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIUdiul9N-Lr7h4HJdQ-QSVE-_lO80GGQ',
    appId: '1:634110584934:web:3580aa588e25977feca5a7',
    messagingSenderId: '634110584934',
    projectId: 'raabta-8a961',
    authDomain: 'raabta-8a961.firebaseapp.com',
    storageBucket: 'raabta-8a961.firebasestorage.app',
  );

}